WITH x(MSG) AS (
    SELECT SUBSTR(REGEXP_REPLACE(MSG, '\d+', '%'), 1, 150) FROM SIO_MDM_LOG WHERE LVL = 'ERR' AND ID BETWEEN ##beg_id## AND nvl(##end_id##, id)
)
SELECT COUNT(1) num, MSG FROM x GROUP BY MSG ORDER BY 1 DESC