SELECT Z.KODP, O.NAME, X.CUR_YM, X.DT
  FROM KS_ZBD Z JOIN KR_ORG O ON (Z.KODP = O.KODP) 
  JOIN (SELECT MAX (C.YM) AS CUR_YM, MAX (C.D_M) AS DT, C.PODR FROM KR_CALC C GROUP BY C.PODR) X ON (Z.KODP = X.PODR)
 WHERE O.PR_ACTIVE = 0