WITH x AS (
    SELECT '6.1' AS tab, COUNT(1) AS row_num, COUNT(DISTINCT FILENAME) AS file_num FROM SIO_MSG6_1
    UNION ALL
    SELECT '13.1', COUNT(1), COUNT(DISTINCT FILENAME) FROM SIO_MSG13_1
    UNION ALL
    SELECT '16.1', COUNT(1), COUNT(DISTINCT FILENAME) FROM SIO_MSG16_1
)
SELECT SYSDATE DT, 684014 - SUM(FILE_NUM) NUM FROM x