WITH 
x(FLOW_TYPE, KOD_OBJTYPE, NAME, SOUR, TAG, CATEG, NUM) AS (
    SELECT s.FLOW_TYPE, s.KOD_OBJTYPE, t.NAME, s.SOUR, s.TAG, decode(s.SOUR, 'SEG', DECODE(s.TAG, NULL, 'NOPAIR', 'CH', 'ADDED', 'PAIRED'), 'ERROR') categ, s.NUM  
      FROM VI_HANDLE_STAT s, IEK_OBJTYPE t
     WHERE s.KOD_OBJTYPE = t.KOD_OBJTYPE
 ),
d(FLOW_TYPE, KOD_OBJTYPE, ORD) AS (
    SELECT DISTINCT FLOW_TYPE, KOD_OBJTYPE, DECODE(KOD_OBJTYPE, 1, 2, 2, 1, KOD_OBJTYPE) FROM x
 ),
 found(FLOW_TYPE, KOD_OBJTYPE, NUM) AS (
    SELECT FLOW_TYPE, KOD_OBJTYPE, SUM(NUM) FROM x WHERE SOUR = 'SEG' AND TAG IN ('FF', 'FP') GROUP BY FLOW_TYPE, KOD_OBJTYPE
 ),
 maked(FLOW_TYPE, KOD_OBJTYPE, NUM) AS (
    SELECT FLOW_TYPE, KOD_OBJTYPE, SUM(NUM) FROM x WHERE SOUR = 'SEG' AND TAG = 'CH' GROUP BY FLOW_TYPE, KOD_OBJTYPE
 ),
 nopair(FLOW_TYPE, KOD_OBJTYPE, NUM) AS (
    SELECT FLOW_TYPE, KOD_OBJTYPE, SUM(NUM) FROM x WHERE SOUR = 'SEG' AND TAG IS NULL GROUP BY FLOW_TYPE, KOD_OBJTYPE
 ),
 error(FLOW_TYPE, KOD_OBJTYPE, NUM) AS (
    SELECT FLOW_TYPE, KOD_OBJTYPE, SUM(NUM) FROM x WHERE SOUR = 'ERR' GROUP BY FLOW_TYPE, KOD_OBJTYPE
 )
 SELECT d.FLOW_TYPE, d.KOD_OBJTYPE, t.NAME, nvl(f.num, 0) fnum, nvl(m.num, 0) mnum, nvl(n.num, 0) - nvl(e.num, 0) nnum, nvl(e.num, 0) enum
   FROM d 
   INNER JOIN IEK_OBJTYPE t ON (T.KOD_OBJTYPE = d.KOD_OBJTYPE)
   LEFT OUTER JOIN found f ON (f.FLOW_TYPE = d.FLOW_TYPE AND f.KOD_OBJTYPE = d.KOD_OBJTYPE)
   LEFT OUTER JOIN maked m ON (m.FLOW_TYPE = d.FLOW_TYPE AND m.KOD_OBJTYPE = d.KOD_OBJTYPE)
   LEFT OUTER JOIN nopair n ON (n.FLOW_TYPE = d.FLOW_TYPE AND n.KOD_OBJTYPE = d.KOD_OBJTYPE)
   LEFT OUTER JOIN error e ON (e.FLOW_TYPE = d.FLOW_TYPE AND e.KOD_OBJTYPE = d.KOD_OBJTYPE)
 ORDER BY d.FLOW_TYPE, d.ORD
