SELECT DISTINCT 
    SUBSTR(ATTP_YM, 39) YM, 
    SUBSTR(NOBJ_KOD_NUMOBJ, 27) OBJ_IES,  SUBSTR(ATTP_KOD_ATTPOINT, 27) ATP_IES, 
    to_char(DT, 'dd.mm.yyyy') DT, FILENAME,
    SUBSTR(ATTP_ENERGY, 37) ENRG, SUBSTR(ATTP_METHOD, 44) MTHD, SUBSTR(ATTP_VOLKIND, 45) KIND, 
    SUBSTR(ATTP_KODINTERVAL, 44) INTV, SUBSTR(ATTP_VOLTAGE, 35) VLTG, ATTP_VOL    
  FROM SIO_MSG16_1
 WHERE #field_val# = :key
 ORDER BY 1 DESC, 2 DESC, 3, 4, 5