WITH 
     X AS (
        SELECT IDS, IDS_INF, ID_IES FROM VI_LINKS_IES_GRP
     ),
     ISE AS (
        SELECT /*+ RULE */ * FROM VI_ISE
     ),
     TAB AS (
        SELECT 
            M.ABON_NAME, ISE.ABON_NAME AS PAYER_NAME, M.ABON_INN, ISE.ABON_INN AS PAYER_INN,
            M.ABON_KODP, ISE.KODP, AB.IDS_INF AB_STR_CLL,

            M.DG_NDOG, ISE.NDOG, ISE.DEPNAME,
            DG.ID_IES DG_ID_IES, ISE.KOD_DOG, DG.IDS_INF DG_STR_CL,

            M.NOBJ_NUM, ISE.NUMOBJ_NUM, M.NOBJ_NAME, ISE.NUMOBJ_NAME,
            NOBJ.ID_IES NOBJ_ID_IES, ISE.KOD_NUMOBJ, NOBJ.IDS_INF NOBJ_STR_CLL,            

            M.PNT_NUM, ISE.PNTNO, M.PNT_NAME, ISE.PNTNAME, 
            PNT.ID_IES PNT_ID_IES, ISE.KOD_POINT, PNT.IDS_INF PNT_STR_CLL,
            
            M.PU_NUM, ISE.NOM_PU, M.PU_TYPE, 
            PU.ID_IES PU_ID_IES, ISE.KOD_POINT_PU, PU.IDS_INF PU_STR_CLL,
           

            M.INI_KOD_DIRECTEN, ISE.KOD_DIRECTEN, M.INI_KODINTERVAL, ISE.KODINTERVAL, M.INI_RKOEF, ISE.RKOEFF,
            M.INI_KOD_POINT_INI, ISE.KOD_POINT_INI,
            --
            PR.YM, PR.READPREV, PR.READLAST, PR.OUT
        FROM SIO_MSG6_1 M
            LEFT OUTER JOIN X AB ON (M.ABON_KODP = AB.ID_IES)
            LEFT OUTER JOIN X DG ON (M.DG_KOD_DOG = DG.ID_IES)
            LEFT OUTER JOIN X NOBJ ON (M.NOBJ_KOD_NUMOBJ = NOBJ.ID_IES)
            LEFT OUTER JOIN X PNT ON (M.PNT_KOD_POINT = PNT.ID_IES)
            LEFT OUTER JOIN X PU ON (M.PU_KOD_POINT_PU = PU.ID_IES)
            LEFT OUTER JOIN IER_LINK_OBJECTS INI ON (M.INI_KOD_POINT_INI = INI.ID_IES)
            --
            LEFT OUTER JOIN ISE ON (ISE.KOD_POINT_INI = INI.ID)
            LEFT OUTER JOIN NV_PRIEM PR ON (PR.KOD_POINT_INI = ISE.KOD_POINT_INI AND YM = 2021.02)
        WHERE M.PU_KIND IS NULL
    ),
    RES AS (
        SELECT TAB.* 
          FROM TAB, GLB_SIO_NUMS G
         WHERE 1=1
           AND (G.INN IS NULL OR G.INN = TAB.ABON_INN)
           AND (G.DOG IS NULL OR G.DOG = TAB.DG_NDOG)
           AND (G.OBJ IS NULL OR G.OBJ = TAB.NOBJ_NUM)
           AND (G.PU IS NULL OR G.PU = TAB.PU_NUM)
    )
SELECT res.*
  FROM RES
 ORDER BY RES.NOBJ_NUM, RES.PU_NUM, RES.INI_KODINTERVAL
