SELECT DISTINCT SUBSTR(m16.INI_YM, 39) YM, 
    SUBSTR(m16.NOBJ_KOD_NUMOBJ, 27) OBJ_IES,  SUBSTR(m16.ATTP_KOD_ATTPOINT, 27) ATP_IES, 
    u.PU_NUM, u.PU_KOD_POINT_PU PU_IES, i.INI_KOD_POINT_INI INI_IES, 
    SUBSTR(m16.INI_ENERGY, 37) ENRG, SUBSTR(m16.INI_METHOD, 40) MTHD, SUBSTR(m16.INI_VOLKIND, 45) KIND,
    SUBSTR(m16.INI_KODINTERVAL, 44) INTV, SUBSTR(m16.INI_VOLTAGE, 35) VLTG,
    m16.INI_VOL_DOP, m16.INI_VOL_INT, m16.INI_VOL_Z, m16.INI_VOL_OB, m16.INI_VOL_PU, m16.INI_VOL_DG, m16.INI_VOL_SR, m16.INI_VOL_POTERI, m16.INI_VOL_RAS, m16.INI_VOL_OTHER
    
  FROM SIO_MSG16_1 m16, SIO_MSG13_1 m13, SIO_INI i, SIO_PU u
  WHERE m16.#field_val# = :key
    AND m13.IND_KOD_INDICAT (+) = m16.INI_READLAST
   AND i.INI_KOD_POINT_INI (+) = m13.INI_KOD_POINT_INI
   AND u.PU_KOD_POINT_PU (+) = i.PU_KOD_POINT_PU
 ORDER BY 4, 5, 6, 7
