WITH 
    TIMES AS (SELECT (SELECT MAX(DT) FROM SIO_TIMES WHERE DT < T.DT) AS DT_BEG, T.DT DT_END FROM SIO_TIMES T WHERE ID = :LABEL)
    , ERRS AS (
        SELECT TRAN_ID, MIN(DT) AS DT
          FROM SIO_MDM_LOG, TIMES
         WHERE (:MSG IS NULL OR ERR_GRP LIKE :MSG)
           AND DT BETWEEN NVL(TIMES.DT_BEG, DT) AND TIMES.DT_END
         GROUP BY TRAN_ID
         ORDER BY 2 DESC
    )
SELECT * FROM ERRS