WITH 
    TIMES AS (SELECT (SELECT MIN(DT) FROM SIO_TIMES WHERE DT > T.DT) AS DT_END, T.DT DT_BEG FROM SIO_TIMES T WHERE ID = :label_id)
    , ERRS AS (
        SELECT TRAN_ID, MIN(DT) AS DT
          FROM SIO_MDM_LOG, TIMES
         WHERE (:msg IS NULL OR ERR_GRP LIKE :msg)
           AND DT BETWEEN TIMES.DT_BEG AND NVL(TIMES.DT_END, DT)
         GROUP BY TRAN_ID
         ORDER BY 2 DESC
    )
SELECT * FROM ERRS