WITH 
    FLOWS AS (SELECT COLUMN_VALUE AS FLOW_TYPE FROM TABLE(ASUSETYPES.VARCHAR2$TABLE('ИЖС', 'ЮЛ', 'МКД_КВ'))),
    TAGS AS (SELECT COLUMN_VALUE AS TAG FROM TABLE(ASUSETYPES.VARCHAR2$TABLE('FF', 'FP', 'CH'))),
    OBJ AS (SELECT KOD_OBJTYPE, NAME FROM IEK_OBJTYPE),
    TBL AS (SELECT FLOW_TYPE, TAG, KOD_OBJTYPE, NAME AS TYPE_NAME FROM FLOWS, TAGS, OBJ),
    PAIRS AS (SELECT FLOW_TYPE, TAG, KOD_OBJTYPE, COUNT(1) NUM FROM IER_LINK_OBJECTS GROUP BY FLOW_TYPE, TAG, KOD_OBJTYPE)
SELECT T.FLOW_TYPE, T.KOD_OBJTYPE, T.TYPE_NAME, T.TAG, NVL(P.NUM, 0) NUM
  FROM TBL T
  LEFT OUTER JOIN PAIRS P ON (T.FLOW_TYPE = P.FLOW_TYPE AND T.TAG = P.TAG AND T.KOD_OBJTYPE = P.KOD_OBJTYPE)
 ORDER BY T.FLOW_TYPE, DECODE(T.KOD_OBJTYPE, 1, 2, 2, 1, T.KOD_OBJTYPE), T.TAG