SELECT to_char(l.DT, 'YYYY-MM-DD') DT, p.INN ABN_INN, p.NAME ABN_NAME, d.NDOG DOG_NUM, o.NUM_OBJ OBJ_NUM, o.NAME OBJ_NAME, a.ATTPOINT_NAME ATT_NAME, t.NOMER PNT_NUM, t.NAME PNT_NAME,
f.SNAME DEP_NAME, p.KODP ABN_ID, d.KOD_DOG DOG_ID, o.KOD_NUMOBJ OBJ_ID, a.KOD_ATTPOINT ATT_ID, t.KOD_POINT PNT_ID, d.DEP
  FROM IER_LINK_OBJECTS l, HR_ATTPOINT a, HR_POINT t, KR_NUMOBJ o, KR_DOGOVOR d, KR_PAYER p, KR_ORG f
 WHERE l.KOD_OBJTYPE = 7
   AND l.dt BETWEEN TO_DATE(:beg, 'YYYY-MM-DD') AND TO_DATE(:end, 'YYYY-MM-DD')
   AND l.TAG = 'CH'
   AND t.KOD_POINT = l.ID
   AND t.KOD_ATTPOINT = a.KOD_ATTPOINT
   AND o.KOD_OBJ = t.KOD_OBJ
   AND d.KOD_DOG = o.KOD_DOG
   AND P.KODP = d.KODP
   AND f.KODP = d.DEP
   AND d.dep = :dep
 ORDER BY 2, 3, 4, 5
