SELECT to_char(l.DT, 'YYYY-MM-DD') DT, p.INN ABN_INN, p.NAME ABN_NAME, d.NDOG DOG_NUM, f.SNAME DEP_NAME, p.KODP ABN_ID, d.KOD_DOG DOG_ID, d.DEP
  FROM IER_LINK_OBJECTS l, KR_DOGOVOR d, KR_PAYER p, KR_ORG f
 WHERE l.KOD_OBJTYPE = 1 
   AND l.dt BETWEEN TO_DATE(:beg, 'YYYY-MM-DD') AND TO_DATE(:end, 'YYYY-MM-DD')
   AND l.TAG = 'CH'
   AND d.KOD_DOG = l.ID
   AND P.KODP = d.KODP
   AND f.KODP = d.DEP
   AND d.dep = :dep
 ORDER BY 2, 3, 4, 5