SELECT COUNT(1) num, ERR_GRP as MSG 
  FROM SIO_MDM_LOG 
 WHERE LVL = 'ERR'
   AND ID BETWEEN ##beg_id## AND nvl(##end_id##, id)
 GROUP BY ERR_GRP ORDER BY 1 DESC

-- WITH x(MSG) AS (
--     SELECT /*+ RULE */ SUBSTR(REGEXP_REPLACE(MSG, '\d+', '%'), 1, 150) FROM SIO_MDM_LOG WHERE LVL = 'ERR' AND ID BETWEEN ##beg_id## AND nvl(##end_id##, id)
-- )
-- SELECT COUNT(1) num, MSG FROM x GROUP BY MSG ORDER BY 1 DESC